/* project-descriptions.ts */

import type { Project, ProjectDescriptions } from '../types';

export const projectsData: Project[] = [
  // --- NARRATIVE SYSTEMS (Landscape) ---
  {
    title: 'Skywalker',
    tag: 'Movie-Narrative Guide',
    desc: "An immersive mythic companion using Luke Skywalker's journey as a mirror for personal growth.",
    href: 'https://benwassa.github.io/Skywalker/',
    img: 'assets/projects/Skywalker.png',
    alt: 'Skywalker - Narrative System',
    theme: { primary: '#3B82F6', secondary: '#1F2937', tertiary: '#151720', bg: '#0A0B14' },
    status: 'active',
    type: 'narrative',
    orientation: 'landscape',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/Skywalker',
    demoMode: 'none',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Single-Page Narrative',
      stack: ['HTML', 'CSS', 'JavaScript'],
      features: ['Audio Playback', 'Guided Prompts', 'Custom AI Artwork'],
    },
  },
  {
    title: 'Sankofa',
    tag: 'Scientific-Narrative Guide',
    desc: 'A unified framework addressing the Modern Meaning Crisis through mythic storytelling.',
    href: 'https://benwassa.github.io/sankofa/',
    img: 'assets/projects/Sankofa.png',
    alt: 'Sankofa - Narrative System',
    theme: { primary: '#d4af37', secondary: '#2d2520', tertiary: '#1a1a1a', bg: '#0a0a0a' },
    status: 'active',
    type: 'narrative',
    orientation: 'landscape',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/sankofa',
    demoMode: 'none',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Static Narrative Site',
      stack: ['HTML', 'CSS', 'JavaScript'],
      features: ['Audio Playback', 'Long-Form Content', 'Multimedia Content'],
    },
  },
  {
    title: 'Dukkha',
    tag: 'Scientific-Narrative Guide',
    desc: 'A field guide on dopamine as a cultural force and tool for digital autonomy.',
    href: 'https://benwassa.github.io/dukkha/',
    img: 'assets/projects/Dukkha.png',
    alt: 'Dukkha - Digital well-being',
    theme: { primary: '#10b981', secondary: '#1f2937', tertiary: '#111827', bg: '#0f172a' },
    status: 'draft',
    type: 'psychology',
    orientation: 'landscape',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/dukkha',
    demoMode: 'none',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Interactive Guide',
      stack: ['Python', 'HTML', 'CSS'],
      features: ['Interactive Content', 'Research Synthesis'],
    },
  },
  {
    title: 'Agoge',
    tag: 'Scientific-Narrative Guide',
    desc: 'A cross-cultural study of rites of passage reimagined for modern resilience.',
    href: 'https://benwassa.github.io/agoge/',
    img: 'assets/projects/Agoge.png',
    alt: 'Agoge - Rites of passage',
    theme: { primary: '#dc2626', secondary: '#7f1d1d', tertiary: '#1c1917', bg: '#0c0a09' },
    status: 'draft',
    type: 'narrative',
    orientation: 'landscape',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/agoge',
    demoMode: 'none',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Narrative Research',
      stack: ['Python', 'Markdown'],
      features: ['Audio Playback', 'Cross-Cultural Analysis', 'Mythic Structure'],
    },
  },
  {
    title: 'Orpheus',
    tag: 'Music Research Tool',
    desc: 'A lyrical lantern decoding the themes in your listening patterns.',
    href: null,
    img: 'assets/projects/Orpheus.png',
    alt: 'Orpheus - Audio Analysis',
    theme: { primary: '#8B5CF6', secondary: '#1e1b4b', tertiary: '#1e293b', bg: '#0f0f23' },
    status: 'draft',
    type: 'psychology',
    orientation: 'landscape',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/orpheus',
    demoMode: 'none',
    techSpecs: {
      model: 'Data Analysis Tool',
      stack: ['Python', 'pandas', 'Streamlit'],
      features: ['Listening Pattern Charts', 'Audio Analysis'],
    },
  },

  // --- SYSTEMS & APPS (Square) ---
  {
    title: 'drop',
    tag: 'Daily Domain Tracker',
    desc: 'Setting, tracking, and reviewing habit consistency.',
    href: 'https://benwassa.github.io/drop/',
      demoUrl: 'https://benwassa.github.io/drop/',
    img: 'assets/projects/drop.png',
    alt: 'drop - Tracker',
    theme: { primary: '#3b82f6', secondary: '#1c1c21', tertiary: '#0b0b0f', bg: '#09090b' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/drop',
    demoMode: 'live',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Offline-First PWA',
      stack: ['JavaScript', 'HTML', 'CSS'],
      features: ['Offline-First', 'IndexedDB Storage', 'Daily Scoring'],
    },
  },
  {
    title: 'STARK',
    tag: 'Fitness Intelligence',
    desc: 'Fitness intelligence dashboard for strength, endurance, recovery.',
    href: 'https://benwassa.github.io/STARK/',
      demoUrl: 'https://benwassa.github.io/STARK/',
    img: 'assets/projects/STARK.png',
    alt: 'STARK - Fitness PWA',
    theme: { primary: '#d4956d', secondary: '#b06a3a', tertiary: '#8b5c3c', bg: '#3d2a1f' },
    status: 'prototype',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/STARK',
    demoMode: 'live',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Client-Side Dashboard',
      stack: ['React', 'TypeScript', 'Tailwind'],
      features: ['Fitness Metrics Dashboard', 'IndexedDB Storage', 'Animated UI'],
    },
  },
  {
    title: 'Vox',
    tag: 'Language Learning Tracker',
    desc: 'Vocabulary and grammar studying tool.',
    href: 'https://benwassa.github.io/Vox_Showcase/',
    img: 'assets/projects/Vox.png',
    alt: 'Vox - Language Tool',
    theme: { primary: '#d4956d', secondary: '#b06a3a', tertiary: '#8b5c3c', bg: '#3d2a1f' },
    status: 'prototype',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/Vox',
    demoMode: 'template',
    techSpecs: {
      model: 'Offline-First App',
      stack: ['JavaScript', 'JSON'],
      features: ['Offline-First', 'Local Storage', 'Spaced Repetition'],
    },
  },
  {
    title: 'Punchbuggy',
    tag: 'Game',
    desc: 'Minimalist punchbuggy game with instant feedback.',
    href: 'https://benwassa.github.io/punchbuggy/',
      demoUrl: 'https://benwassa.github.io/punchbuggy/',
    img: 'assets/projects/punchbuggy.png',
    alt: 'Punchbuggy - Game',
    theme: { primary: '#3b82f6', secondary: '#1f2937', tertiary: '#374151', bg: '#111827' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/punchbuggy',
    demoMode: 'live',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Instant Game PWA',
      stack: ['JavaScript', 'Vite'],
      features: ['No Account Required', 'No Gamification Loops', 'Offline-First'],
    },
  },
  {
    title: 'Hearth',
    tag: 'Shared Watchlist',
    desc: 'A shared watchlist for couples with TMDB metadata and a portfolio-safe demo mode.',
    href: 'https://hearthv2--hearthv2.us-east4.hosted.app/?mode=demo',
      demoUrl: 'https://hearthv2--hearthv2.us-east4.hosted.app/?mode=demo',
    img: 'assets/projects/hearth.png',
    alt: 'Hearth - Watchlist',
    theme: { primary: '#aa6c4b', secondary: '#be185d', tertiary: '#831843', bg: '#3f0f4d' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/hearth_v2',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Firebase-Backed Watchlist App',
      stack: ['React', 'JavaScript', 'Firebase', 'Node.js', 'Express', 'Tailwind'],
      features: ['External API Integration', 'Real-Time Sync', 'Demo Mode'],
    },
  },
  {
    title: 'PushUp Challenge',
    tag: 'Fitness Challenge App',
    desc: 'Pushup challenge tracker with community accountability.',
    href: 'https://benwassa.github.io/the-pushup-challenge-2025/?mode=demo',
      demoUrl: 'https://benwassa.github.io/the-pushup-challenge-2025/?mode=demo',
    img: 'assets/projects/pushup.png',
    alt: 'PushUp - Fitness App',
    theme: { primary: '#ef4444', secondary: '#b91c1c', tertiary: '#7f1d1d', bg: '#4c0519' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/the-pushup-challenge-2025',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Community Tracker',
      stack: ['React', 'Firebase'],
      features: ['Leaderboard', 'Community Progress Tracking'],
    },
  },
  {
    title: 'Wrestle',
    tag: 'Grappling Training Log',
    desc: 'Training log for wrestlers: mat hours, intensity and consistency.',
    href: 'https://benwassa.github.io/wrestlePWA/',
    demoUrl: 'https://benwassa.github.io/wrestlePWA/demo/',
    img: 'assets/projects/wrestle.png',
    alt: 'Wrestle - Log',
    theme: { primary: '#d4956d', secondary: '#b06a3a', tertiary: '#8b5c3c', bg: '#3d2a1f' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/wrestlePWA',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Offline-First PWA',
      stack: ['JavaScript', 'Tailwind', 'Firebase', 'Vite'],
      features: ['Anonymous Cloud Sync', 'Offline Sync Queue', 'Training Trend Charts'],
    },
  },
  {
    title: 'Narrative',
    tag: 'Travel Photo Organizer',
    desc: 'Keyboard-first curation of travel photos by story role.',
    href: 'https://benwassa.github.io/Narrative/',
    demoUrl: 'https://benwassa.github.io/narrative-template/',
    img: 'assets/projects/narrative.png',
    alt: 'Narrative - Photo Tool',
    theme: { primary: '#84cc16', secondary: '#65a30d', tertiary: '#4b5320', bg: '#202601' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/Narrative',
    demoMode: 'template',
    techSpecs: {
      model: 'Local-First Utility',
      stack: ['React', 'TypeScript', 'Vite', 'Tailwind'],
      features: ['File System Access', 'IndexedDB Storage', 'Rename Script Export'],
    },
  },
  {
    title: 'Morpheus',
    tag: 'Dream Archive',
    desc: 'A glassmorphic archive for structured dream entries and scene images.',
    href: 'https://benwassa.github.io/template-morpheus/',
    demoUrl: 'https://benwassa.github.io/template-morpheus/',
    img: 'assets/projects/morpheus.png',
    alt: 'Morpheus - Journal',
    theme: { primary: '#8b5cf6', secondary: '#6d28d9', tertiary: '#4c1d95', bg: '#2e1065' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/morpheus-dream-archive',
    demoMode: 'template',
    techSpecs: {
      model: 'Private Journaling PWA',
      stack: ['React', 'Vite', 'Tailwind', 'Firebase'],
      features: ['AI-Structured Entry Import', 'Scene Image Storage', 'Glassmorphism UI'],
    },
  },
  {
    title: 'Poseidon',
    tag: 'Dive Journal',
    desc: 'A dive journal that turns every logged dive into a personal marine atlas.',
    href: 'https://benwassa.github.io/poseidon/',
    demoUrl: 'https://benwassa.github.io/poseidon/demo/',
    img: 'assets/projects/poseidon.png',
    alt: 'Poseidon - Dive Journal',
    theme: { primary: '#22a3c9', secondary: '#0b5e7e', tertiary: '#083f54', bg: '#04212e' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/poseidon',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Offline-First PWA',
      stack: ['React', 'TypeScript', 'Tailwind', 'Firebase'],
      features: ['Illustrated Creature Catalogue', 'Offline Persistence', 'Demo Mode'],
    },
  },
  {
    title: 'Argus',
    tag: 'Spaced Repetition',
    desc: 'Spaced-repetition learning for finite skills you can actually finish.',
    href: 'https://benwassa.github.io/argus/',
    demoUrl: 'https://benwassa.github.io/argus/',
    img: 'assets/projects/argus.png',
    alt: 'Argus - Learning App',
    theme: { primary: '#cbd5e1', secondary: '#2b3038', tertiary: '#1a1d22', bg: '#101215' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/argus',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Local-First Learning App',
      stack: ['React', 'TypeScript', 'Vite', 'Firebase'],
      features: ['Spaced Repetition Scheduler', 'Web Audio Morse Drills', 'Demo Mode'],
    },
  },
  {
    title: 'HAUS',
    tag: 'Household Task Manager',
    desc: 'Shared household tasks, ranked by what can actually get done today.',
    href: 'https://benwassa.github.io/HAUS/',
    demoUrl: 'https://benwassa.github.io/HAUS/',
    img: 'assets/projects/haus.png',
    alt: 'HAUS - Household Tasks',
    theme: { primary: '#e0a948', secondary: '#a16d32', tertiary: '#5c3d22', bg: '#2b1d12' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/HAUS',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Firebase-Backed Shared App',
      stack: ['React', 'Vite', 'Tailwind', 'Firebase'],
      features: ['Urgency × Importance Matrix', 'Real-Time Sync', 'Demo Mode'],
    },
  },
  {
    title: 'Flag',
    tag: 'Geography Trainer',
    desc: 'Learn world flags, locations, outlines and neighbours on a 3D Earth.',
    href: 'https://benwassa.github.io/flag/',
    demoUrl: 'https://benwassa.github.io/flag/',
    img: 'assets/projects/flag.png',
    alt: 'Flag - Geography App',
    theme: { primary: '#7fb77e', secondary: '#1a4a66', tertiary: '#12283a', bg: '#0d1117' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/flag',
    demoMode: 'live',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Offline-First PWA',
      stack: ['React', 'TypeScript', 'Three.js', 'Vite'],
      features: ['Interactive 3D Globe', 'Region Mastery Tracking', 'Optional Cloud Backup'],
    },
  },
  {
    title: "Chef's Journal",
    tag: 'Cooking Journal',
    desc: 'A shared household cooking journal with ratings, a cookbook and a shopping list.',
    href: 'https://benwassa.github.io/chefs-journal/',
    demoUrl: 'https://benwassa.github.io/chefs-journal/',
    img: 'assets/projects/chefs-journal.png',
    alt: "Chef's Journal - Cooking Journal",
    theme: { primary: '#f43f5e', secondary: '#4f46e5', tertiary: '#312e81', bg: '#1e1b4b' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/chefs-journal',
    demoMode: 'playbook',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Firebase-Backed PWA',
      stack: ['React', 'Vite', 'Tailwind', 'Firebase'],
      features: ['Shared Household Journal', 'Structured Ingredient Logging', 'Demo Mode'],
    },
  },
  {
    title: 'Ecological Constellation',
    tag: 'Personality Framework',
    desc: 'A personality framework mapping Big Five traits to ecological strategies.',
    href: 'https://benwassa.github.io/ecological-constellation/',
    img: 'assets/projects/ecological.png',
    alt: 'Ecological Constellation',
    theme: { primary: '#06b6d4', secondary: '#0891b2', tertiary: '#164e63', bg: '#082f4f' },
    status: 'active',
    type: 'app',
    orientation: 'square',
    tier: 'featured',
    repoUrl: 'https://github.com/BenWassa/ecological-constellation',
    demoMode: 'none',
    lastVerified: '2026-10-02',
    techSpecs: {
      model: 'Interactive Visualization',
      stack: ['React', 'TypeScript'],
      features: ['WebGL Rendering', 'Interactive Modeling'],
    },
  },
];

export const projectDescriptions: ProjectDescriptions = {
  skywalker: {
    portfolio:
      'A comprehensive UX playground for personal systems and compounding routines with advanced interaction patterns.',
    full: "The Skywalker Quest Map is an immersive mythic companion for personal reflection and philosophical growth, using Luke Skywalker's journey as a timeless mirror for your own. It transforms passive listening into active self-discovery through structured prompts, symbolic insight, and guided questions - weaving classic mythic stages into modern psychological reflection. Thoughtfully designed for slow, deliberate use, it invites you to map your inner conflicts, inheritances, shadows, and redemptions, all within a poetic, soul-centered framework that honors myth not as fantasy but as a living guide for becoming.",
  },

  sankofa: {
    portfolio:
      'An immersive mythic psychology narrative experience with podcast scaffolding in a living document environment.',
    full: 'Project Sankofa is an overarching narrative framework to tackle the Modern Meaning Crisis. It weaves mythic storytelling, cultural critique, and deep research into a unified exploration of how contemporary life lost cohesive meaning - and how people might find soul, purpose, and moral compass again. Sankofa ties together dopamine work, rites of passage concepts, and narrative design into a podcast or multimedia experience that blends rigorous insight with emotionally resonant mythic arcs.',
  },

  dukkha: {
    portfolio:
      'A comprehensive field guide for digital discipline - featuring live HTML experiences & systematic UX patterns.',
    full: 'Project Dukkha is a field guide and manifesto for understanding dopamine not just as a neurotransmitter but as a living, mythic force shaping human culture, motivation, habits, and collective drift. It aims to reveal misconceptions, chart how dopamine-driven systems fuel modern temptations and crises, and offer practical tools to navigate daily life with more clarity and autonomy.',
  },

  vox: {
    portfolio:
      'Advanced language-learning dashboard with progress tracking, analytics, and adaptive learning algorithms (in development).',
    full: 'Vox is a pilot framework for building a rigorous, self-directed language learning system. It emphasizes grammar mastery, transparent vocab tracking, and real-world sentence production - eschewing gamified fluff in favor of deliberate, adaptive practice. Designed to function fully offline with clean JSON architecture, Vox visualizes progress like a growing reservoir of knowledge, where vocabulary adds volume, grammar shapes the container, and output waters the fields of fluency. It serves as both prototype and proof-of-concept for a learner-first, data-transparent alternative to mainstream apps.',
  },

  orpheus: {
    portfolio:
      'Experimental audio interfaces and sonic interaction patterns - exploring the intersection of sound and digital experience.',
    full: 'Project Orpheus is a lyrical lantern into the underworld of memory and emotion. By tracing the songs you play on repeat - the fixations, the phases, the sudden crescendos - it reveals the hidden narratives shaping your life. Like Orpheus descending with music as his guide, this framework transforms passive listening into active self-discovery through structured analysis, mythic symbolism, and reflective prompts. Thoughtfully designed for slow, deliberate exploration, it lets you chart emotional currents, pivotal transitions, and unmet needs inside a poetic, soul-centered map where every refrain becomes a clue to becoming more wholly yourself.',
  },

  agoge: {
    portfolio:
      'A narrative research project exploring traditional rites of passage and authentic initiation for the modern world.',
    full: "Project Agoge is a narrative research project exploring how traditional rites transformed boys into grounded, resilient men. It blends cross-cultural history, mythic symbolism, and modern psychology to uncover timeless insights on confidence, moral strength, and belonging - laying the groundwork for a podcast and supporting framework that reimagines authentic initiation for today's world.",
  },

  stark: {
    portfolio:
      'A data visualization PWA that unifies strength, endurance, mobility, and recovery into one elegant Fitness Index, complete with VO2 max and trend insights.',
    full: 'STARK is a static Progressive Web App built with React and TailwindCSS, designed to turn physiological data into a clear visual story of fitness and recovery. It blends performance metrics, VO2 max estimation, and normative comparisons into an elegant offline dashboard that values transparency, simplicity, and privacy. All calculations are client-side, data is stored in IndexedDB, and users can install it as a PWA - no logins, no servers, just insight.',
  },

  drop: {
    portfolio:
      'A mindful daily tracker for Sleep, Fitness, Mind, and Spirit - built as a pure vanilla JavaScript PWA that values quality, reflection, and sustained growth over streaks or perfection.',
    full: "drop is a minimalist, framework-free Progressive Web App designed for reflective self-tracking across four life domains: Sleep, Fitness, Mind, and Spirit. It integrates a philosophically grounded scoring model based on weighted trends and intrinsic motivation, emphasizing balance, consistency, and self-awareness. The app runs fully offline, includes IndexedDB auto-backups, and features an elegant interface optimized for touch and accessibility. It's a digital companion for maintaining mindful engagement with your growth - not a habit tracker, but a quality tracker.",
  },

  punchbuggy: {
    portfolio: 'A minimalist game PWA—no punchbacks, just instant feedback and genuine enjoyment.',
    full: "Punchbuggy is a game designed for pure play. It strips away gamification, accounts, and complexity to deliver immediate, honest fun. Built for quick sessions and infinite replayability, it proves that elegance and engagement don't require addiction mechanics.",
  },

  hearth: {
    portfolio:
      'A shared watchlist app for couples with TMDB-backed metadata, real-time sync, and a portfolio-safe demo mode.',
    full: 'Hearth is a collaborative watchlist app built to reduce decision fatigue when choosing what to watch together. It combines a React frontend, Firebase Auth + Firestore persistence, and a Node/Express API layer that proxies and normalizes TMDB metadata. The product supports shared spaces, show episode progress, and a streamlined Tonight flow, with a dedicated `?mode=demo` path for reliable portfolio testing without affecting live user data.',
  },

  pushupchallenge: {
    portfolio:
      'A time-bound fitness app supporting the Pushup Challenge with tracking and community accountability.',
    full: 'PushUp Challenge is a specialized app built for the annual Pushup Challenge. It provides clean tracking of daily progress, community leaderboards, and sustainable progression without gamification. Designed for participants who take the challenge seriously and want transparent data.',
  },

  wrestle: {
    portfolio:
      'An offline-first training log for wrestlers that signs each visitor in anonymously and keeps their sessions in the cloud.',
    full: 'Wrestle (MatMind in the app) is built for grapplers. Each session records duration, intensity, session type and technique notes, and the dashboard turns them into a rank earned through mat hours, a 30-day consistency heatmap, and volume-versus-intensity charts. Every visitor is signed in anonymously and their log lives in Firestore, behind an offline-first PWA shell that queues writes and syncs them when the connection returns. The embedded demo is a fictional wrestler with seeded history and no backend; it resets on reload.',
  },

  narrative: {
    portfolio:
      'A local-first, keyboard-driven travel photo curation tool that sorts a trip by story role and exports a safe rename script.',
    full: 'Narrative curates a trip by story role instead of by timestamp. It reads a trip folder straight off disk, groups the photos by day, and assigns each shot a role with a single keystroke: A–E for the story, M for mood and food, X to archive. It then generates a copy-based rename script, so the originals are never touched. Everything stays in the browser (Chromium, for folder access). The embedded demo is a separate sample - a preset project of stock photos built from an earlier version of the app.',
  },

  morpheus: {
    portfolio:
      'An installable dream archive: paste AI-structured JSON of a dream, attach scene images, and browse the entries as a card gallery.',
    full: 'Project Morpheus is a private dream archive, with part of the workflow intentionally happening outside the app. A dream is structured into JSON with a bundled AI prompt, pasted in alongside scene images from your preferred image tool, and joins a glassmorphic card gallery. The real app is an installable PWA on Firestore and Storage (v1.7.6, July 2026), behind Google sign-in. The embedded demo is a sample archive on an older template snapshot: it shows the gallery and reading experience, not the current app.',
  },

  poseidon: {
    portfolio:
      'A mobile-first dive journal PWA: log each dive, pick the creatures you met from an illustrated marine catalogue, and build a personal collection and Atlas.',
    full: 'Poseidon is a personal atlas of an underwater life. Logging a dive ends with the part that matters most: choosing the creatures you met from an illustrated marine catalogue. Every dive feeds a journal, a growing creature collection and an Atlas of places dived, persisted locally and exportable as JSON. The real app sits behind Google sign-in; the embedded demo runs on sample dives held in memory and resets on reload.',
  },

  argus: {
    portfolio:
      'A spaced-repetition app built on finite competencies - NATO alphabet, Morse, compass bearings - each with a scored boundary, so it can actually be finished.',
    full: "Argus treats some knowledge as finite and finishable. Each topic - the NATO alphabet, Morse A–Z, compass bearings - declares a scored boundary and counts as complete only once it survives delayed recall. Learn is ungraded practice; Test is the single scored interaction, and a scheduler decides whether a result advances retention. Production syncs across the owner's devices via Google sign-in; the embedded demo is a local-only build on sample progress that resets on reload.",
  },

  haus: {
    portfolio:
      'A phone-first shared household task manager that ranks every task by urgency × importance × resource fit.',
    full: 'HAUS plans housework around the session, not the backlog. A household joins with a six-character code and shares one view of every room and task - there are no private lists. The Planning View scores each task by urgency × importance × resource fit, so work that suits the people present and the hours available rises to the top, while tasks with absent assignees or too little time sink. Production runs on Firebase with real-time sync; the embedded demo swaps in a seeded sample household with no sign-in and resets on refresh.',
  },

  flag: {
    portfolio:
      'An offline-capable geography PWA for flags, locations, outlines and land-border neighbours, navigated through an interactive 3D Earth.',
    full: 'Flag (Atlas in the app) teaches world geography across four domains: the flags of 195 sovereign states, country locations, outlines, and land-border neighbours. You choose a domain, turn an interactive Earth to pick a continent or region, then start Learn for familiarisation or Play for scored recall. Mastery is tracked per region and domain and kept deliberately scarce, so a gold region or the World Crown means something. Progress stays on the device, with optional Google sign-in for backup - which is why the card embeds the production app as-is.',
  },

  chefsjournal: {
    portfolio:
      "A household cooking journal PWA for logging the meals you cook, with ratings, a cookbook and a shared shopping list.",
    full: "Chef's Journal is a shared record of what a household actually cooks. Each meal is logged with structured ingredients, taste, texture and visuals ratings, photos and notes, and builds into favourites and stats over time. A cookbook holds the recipes and a shopping list keeps the next trip in one place. Production is a Google sign-in PWA on Firestore, shared between household members; the embedded demo runs on a sample journal of fictional meals with no sign-in, and nothing is saved.",
  },

  ecologicalconstellation: {
    portfolio:
      'A personality framework mapping Big Five traits to ecological strategies rather than fixed types.',
    full: 'Ecological Constellation reimagines personality through an ecological lens. Instead of fixed types, it maps how Big Five traits function as adaptive strategies in different contexts. It reveals how your personality serves you and where it might limit you—emphasizing flexibility, context, and growth.',
  },
};
